version: '3.9'

services:
  php:
    image: php:8.3-fpm
    container_name: php
    volumes:
      - ../degustabox-time-traker:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && php-fpm"

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: degusta
      MYSQL_USER: degusta_user
      MYSQL_PASSWORD: degusta_password
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../degustabox-time-traker:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      
networks:
  default:
    name: degusta-net